export const LISTINGS: any = [
	{
		transaction_id: 1,
		user_id: 20,
		classDept: 'COM SCI',
		classNum: '35L',
		classTitle: 'Software Construction Labroatory',
		classWanted: ['COM SCI 32', 'COM SCI 118', 'COM SCI 120'],
		instructor: 'Eggert, P.',
		lecture: '3A',
	},
	{
		transaction_id: 2,
		user_id: 20,
		classDept: 'COM SCI',
		classNum: '32',
		classTitle: 'Intro to CS II',
		classWanted: ['COM SCI 32', 'COM SCI 131', 'COM SCI 120'],
		instructor: 'Nachenberg, C.',
		lecture: '2F',
	},
	{
		transaction_id: 3,
		user_id: 20,
		classDept: 'COM SCI',
		classNum: '31',
		classTitle: 'Intro to CS I',
		classWanted: ['COM SCI 32', 'COM SCI 118', 'COM SCI M146'],
		instructor: 'Smallberg, D.',
		lecture: '1C',
	},
	{
		transaction_id: 4,
		user_id: 21,
		classDept: 'COM SCI',
		classNum: '35L',
		classTitle: 'Software Construction Labroatory',
		classWanted: ['COM SCI 295', 'COM SCI 118', 'COM SCI 120'],
		instructor: 'Eggert, P.',
		lecture: '3D',
	},
	{
		transaction_id: 5,
		user_id: 21,
		classDept: 'COM SCI',
		classNum: '32',
		classTitle: 'Intro to CS II',
		classWanted: ['COM SCI 32', 'COM SCI 260B', 'COM SCI 120'],
		instructor: 'Nachenberg, C.',
		lecture: '2A',
	},
	{
		transaction_id: 6,
		user_id: 21,
		classDept: 'COM SCI',
		classNum: '31',
		classTitle: 'Intro to CS I',
		classWanted: ['COM SCI 32', 'COM SCI M226C', 'COM SCI 120'],
		instructor: 'Smallberg, D.',
		lecture: '1E',
	},
];
